### ISSUE TITLE
[공통컴포넌트] header 컴포넌트 변경

### ISSUE THREAD

**Issue by NamgyungKim** [prgrms-fe-devcourse/FEDC2_2JAVATAYO_Dongyoung#120]
# 개요
header 컴포넌트 변경

# 작업 내용

# 사진
![image](https://user-images.githubusercontent.com/87519250/173671633-a2878171-d132-4ed5-ae69-cd820431c462.png)

**Comment by hyunjin0910** [comment]
```
<S.Loggedout onClick={() => console.log("navigate")}>
            로그인 / 회원가입
          </S.Loggedout>
```

onClick시 `console.log` 대신  `navigate("/signin")`으로 변경 필요
